[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Crux-Alpha-White
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Crux-Alpha-White
GtkTheme=Crux-Alpha-White
IconTheme=Crux-Alpha-White
MetacityTheme=Crux-Alpha-White
